config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :orders
    resources :products do
      resources :stocks
    end
    resources :categories
  end
  devise_for :admins
  authenticated :admin_user do
    root to: "admin#index", as: :admin_root 
  end
  
  get "admin" => "admin#index"
  get "cart" => "carts#show"
  post "checkout" => "checkouts#create"
  get "/success", to: "checkouts#success"
  get "/cancel", to: "checkouts#cancel"
  post "webhooks" => "webhook#stripe"
  
  resources :categories, only: [:show]
  resources :products, only: [:show]
  
  root "home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @main_categories = Category.take(5)
  end
end

app/views/home/index.html.erb
<div class="bg-gray-800 text-white text-center py-20">
    <h1 class="text-5xl font-bold mb-4">FoodApp</h1>
    <p class="text-xl mb-8">Tudo que você precisa para seu lanche</p>
    <%= link_to "Compre Agora", root_path, class: "bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded" %>
</div>

<div class="flex flex-wrap justify-center mt-8 items-center gap-10">
    <% @main_categories.each do |category| %>
        <%= link_to admin_category_path(category) do %>
            <div class="flex flex-col mb-4">
                <h2 class="text-gray-800 font-medium text-lg text-center mb-6">
                    <%= category.name %>
                </h2>
                <%= category.image.present? ? image_tag(category.image.variant(:medium), class: "max-w-lg") : image_tag("https://via.placeholder.com/200") %>
            </div>
        <% end %>
    <% end %>
</div>

<div class="bg-gray-100 py-20 my-10">
    <div class="container mx-auto px-6">
        <h2 class="text-4xl font-bold text-center text-gray-800 mb-8">Depoimentos</h2>
        <div class="flex flex-wrap">
            <div class="w-full md:w-1/3 px-2 mb-4">
                <div class="bg-gray-100 rounded shadow py-4 px-4">
                    <p class="text-gray-800 text-base mb-4">
                        Gostei muito de comprar nesse site
                    </p>
                    <p class="text-gray-500 text-xs">
                        Fulano X
                    </p>
                </div>
            </div>
            <div class="w-full md:w-1/3 px-2 mb-4">
                <div class="bg-gray-100 rounded shadow py-4 px-4">
                    <p class="text-gray-800 text-base mb-4">
                        Plataforma muito interessante
                    </p>
                    <p class="text-gray-500 text-xs">
                        Sicrano X
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>